# Infos on current github runners:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#about-github-hosted-runners

name: Test
on: [pull_request, push]

jobs:
  test_all:
    name: Linting & Tests
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'pull_request' || contains(github.event.head_commit.message, '[test]') }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5

      - name: Prepare Linux
        if: ${{ matrix.os  == 'ubuntu-20.04' }}
        run: |
          sudo apt-get update
          sudo apt-get install \
            libleptonica-dev \
            libtesseract-dev \
            python3-pil \
            tesseract-ocr \
            tesseract-ocr-eng

      - name: Prepare MacOS
        if: ${{ matrix.os  == 'macos-10.15' }}
        run: |
          brew install pkg-config tesseract
          brew info tesseract
          ls -R /usr/local/Cellar/tesseract/
          ls -R /usr/local/Cellar/leptonica/

      - name: Prepare Windows 1/2
        if: ${{ matrix.os  == 'windows-2019' }}
        run: poetry install
        continue-on-error: true
      - name: Prepare Windows 2/2
        if: ${{ matrix.os  == 'windows-2019' }}
        run: poetry run pip install https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.4.0-tesseract-4.0.0/tesserocr-2.4.0-cp37-cp37m-win_amd64.whl

      - name: Poetry install
        run: |
          poetry install
          poetry run python build.py download-tessdata

      # TEST WORKFLOW SPECIFIC
      - name: Pylint
        run: poetry run pylint src/normcap src/tests/
      - name: Mypy
        run: poetry run mypy .
      - name: Black
        run: poetry run black --check .
      - name: Isort
        run: poetry run isort --check .
      - name: Pytest on Linux
        if: ${{ matrix.os  == 'ubuntu-20.04' }}
        # libxkbcommon and xvfb is needed to test qt/ui specific things
        run: |
          sudo apt-get install \
            xvfb \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-xfixes0
          poetry run pytest -m "not skip_on_gh_linux"
        env:
          XDG_SESSION_TYPE: gnome
      - name: Pytest on Windows
        if: ${{ matrix.os  == 'windows-2019' }}
        run: poetry run pytest
        env:
          TESSDATA_PREFIX: D:\a\normcap\normcap\src\normcap\resources\tessdata
      - name: Pytest on MacOS
        if: ${{ matrix.os  == 'macos-10.15' }}
        run: poetry run pytest
      - name: Coveralls
        if: ${{ matrix.os  == 'ubuntu-20.04' }}
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
